# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Increment version"
    lane :increment_version do
        increment_version_code(
         gradle_file_path: "./app/build.gradle.kts",
        )

        increment_version_name(
          gradle_file_path: "./app/build.gradle.kts",
        )
    end

    desc "Build release app bundle"
    lane :buildBundle do
      #Please note this is not necessary as far as you have configured the keystore_properties on the gradle.
      # Initialize keystore_properties hash
      keystore_properties = {}

      # Open keystore properties file and read each line
      File.open("../signingConfigs/keystore.properties").each do |line|
        key, value = line.strip.split("=")
        keystore_properties[key] = value if key && value
      end

      # Log the keystore properties to ensure they are read correctly
      puts "Keystore properties: #{keystore_properties}"

      # Run Gradle task to build the app bundle with the properties passed correctly
      gradle(
        task: "clean bundleRelease",
        properties: {
            "signingConfig.release.storePassword" => keystore_properties["storePassword"],
            "signingConfig.release.keyAlias" => keystore_properties["keyAlias"],
            "signingConfig.release.keyPassword" => keystore_properties["keyPassword"],
            "signingConfig.release.storeFile" => keystore_properties["storeFile"],
        }
      )
    end

    desc "This lane build the release APK and Distribute to Internal testers via Firebase"
    lane :uploadReleaseApk do
        increment_version
        gradle(
        task: "clean assemble",
        build_type: "release"
    )
        firebase_app_distribution(
        service_credentials_file: "firebase-app-distribution-key.json",
        app: "1:173373497702:android:9383db37827f6e6974e8a7",
        release_notes: "Integrating Fastlane using bundler",
        groups: "InternalTesters",
        debug: true
    )
    end


    desc "After successful execution of all tasks, Push code to Github"
    after_all do
        git_add(path: "*")
        git_commit(path: "*", message: "increment version code and name")
        push_to_git_remote(local_branch: "main",
                remote: "origin",
                remote_branch: "main", tags: true)
    end
end




# desc "After successful execution of all tasks, Push code to Github"
#     after_all do
#         sh("git add .")
#         sh('git commit -m "increment version code and name"')
#         sh("git push origin main")
#     end























# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
#
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
